### ISSUE TITLE
$url generates empty string with version 1.13

### ISSUE THREAD

**Issue by jeroenlorrentop** [frhagn/Typewriter#218]
When using  Typewriter.Extensions.WebApi with .net 4.6.1 $url generates an empty output.

**Comment by jeroenlorrentop** [comment]
Same issue in 1.14

**Comment by Marcel1024** [comment]
Hi jeroen,

asuming your controllers inherit ApiController, what does this code generate?

```
${
    using Typewriter.Extensions.Types;
    using Typewriter.Extensions.WebApi;
}
$Classes(:ApiController)[
 $Methods[
    $Url;
    ]
]

```

**Comment by jeroenlorrentop** [comment]
We have a baseapicontroller so when I use following template:
```
${
    using Typewriter.Extensions.Types;
    using Typewriter.Extensions.WebApi;
}
$Classes(:BaseApiController)[
 $Methods[
    $Url;
    ]
]
```

Output (for controller with 2 methods): 
 
```
    ;
    
    ;
```

So I created a TestController (which directly inherits ApiController and added a method to it. 

template :
```
${
    using Typewriter.Extensions.Types;
    using Typewriter.Extensions.WebApi;
}
$Classes(:ApiController)[
 $Methods[
    $Url;
    ]
]
```
output:

` /api/Test/;`

**Comment by Marcel1024** [comment]
i see your point...

I created a patch..
what i've done:

controller:
```
[Route("api/[controller]")]
public class BaseController
{
}

public class InheritedController : BaseController
{
      [HttpGet("inherited/{id}")]
      public IEnumerable<string> RoutePrefixFromBaseHttpGetWithParameter(int id)
      {
            return null; // just for testing
      }
}
```

will result in:

`api/Inherited/inherited/${id}`

Does this suit your needs?

**Comment by jeroenlorrentop** [comment]
Yes this patch will probably fix our issues 👍 
Just wondering what could be changed between 1.12 and 1.13 that broke it in the first place.
Just in case it would make a difference: we are not using route attributes, but a global route config.

**Comment by jeroenlorrentop** [comment]
Yes I mean like that. It worked in every version before 1.13

**Comment by frhagn** [comment]
I just published a new version (1.14.1) including @Marcel1024's fix (great work by the way) and a fix for convension-base routing.

**Comment by jeroenlorrentop** [comment]
Just installed the new version, seems like the issue is still there. If I put the route attribute on the controller it works but with convention routing it doesn't.

**Comment by Marcel1024** [comment]
There is a contant variable with default route defined with `api/{controller}/{id?}`

When i run the unit test, on the following class :
```
 public class RouteLessController
    {
        public void Test(int id)
        {
        }
    }

```
The result for $Url = `api/RouteLess/${id}`

Can you post a controller class you use? (may be anonymised, just leave all attributes intact)

**Comment by jeroenlorrentop** [comment]
Just did some additional testing. Looks like it works when no method attributes are used (e.g. HttpGet). 
We are not following the default route but have a route api/{controller}/{action}. With version 1.12 we had to do like this to get the full url: 
` url: "/$Url$Name", `  
It is not the ideal way but worked for us untill now :-)

**Comment by jeroenlorrentop** [comment]
```
[Authorize]
[RightAuthorize(Right.AccessReporting)]
public class TripController : BaseApiController
{
    [HttpPost]
    public TripViewModel GetTrip([FromBody] GetTripRequest req)
    {
        ...
    }
}

```
This is how most of our controllers look like.

**Comment by Marcel1024** [comment]
can you please try the following:

```
${
    // Enable extension methods by adding using Typewriter.Extensions.*
    using Typewriter.Extensions.Types;
    using Typewriter.Extensions.WebApi;
    string GetMyUrl(Method m) => m.Url("/api/{controller}/custom/{action}/{id?}");
}
$Classes(:BaseController)[
    $Methods[
    $GetMyUrl
    ]
]
```

**Comment by jeroenlorrentop** [comment]
> ** on methods without an attribute (httpget/post etc) this should work.
> ** after the merge, it must work on all methods...

Exactly: Without attribute it works. With it doesn't. Will try again when your change is merged 👍 
Thanks for your effort!

**Comment by frhagn** [comment]
Have you had a chance to verify this @jeroenlorrentop? The fix is included in Typewriter 1.14.2

**Comment by jeroenlorrentop** [comment]
Just verified, works as expected. Great work!
